#!/bin/bash
# daily-memory-log.sh
# Creates daily memory files and logs to Supabase memory_logs for ALL agents
# Usage: ./daily-memory-log.sh [AGENT_ID]  (omit agent ID to run for all agents)

set -e

WORKSPACE="${OPENCLAW_WORKSPACE:-/home/ubuntu/.openclaw/workspace}"
TODAY=$(date -u +"%Y-%m-%d")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

SUPABASE_URL="https://lqlnflbzsqsmufjrygvu.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxbG5mbGJ6c3FzbXVmanJ5Z3Z1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDc0ODM3NCwiZXhwIjoyMDg2MzI0Mzc0fQ.k2QS8Z87p91dWhLzOKrBOdEkdfaFWZlVmckHpgJXYIM"

# If specific agent passed, just do that one
if [ -n "$1" ]; then
  AGENTS=("$1")
else
  # Fetch all agent IDs from Supabase
  AGENTS=($(curl -s "${SUPABASE_URL}/rest/v1/agents?select=id&order=id" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" | jq -r '.[].id'))
fi

echo "📝 Daily memory log for ${#AGENTS[@]} agent(s) — ${TODAY}"
echo ""

# Build batch insert for memory_logs
RECORDS="["
FIRST=true

for AGENT_ID in "${AGENTS[@]}"; do
  echo "Processing: ${AGENT_ID}"

  # Create local memory file for HBx (main orchestrator)
  if [ "$AGENT_ID" = "HBx" ]; then
    MEMORY_FILE="${WORKSPACE}/memory/${TODAY}.md"
    if [ ! -f "$MEMORY_FILE" ]; then
      mkdir -p "${WORKSPACE}/memory"
      cat > "$MEMORY_FILE" << EOF
# Memory: ${TODAY}

## Session Summary

Daily status check — automated log.

## Platform Status

- Agents synced from Supabase
- Memory log created: ${TIMESTAMP}

## Notes

- Auto-generated by daily-memory-log.sh
EOF
      echo "  ✅ Created local memory file"
    else
      echo "  ℹ️  Local memory file already exists"
    fi
  fi

  # Add to batch insert
  CONTENT="Daily log: ${AGENT_ID} — ${TODAY}. Platform operating normally."
  if [ "$FIRST" = true ]; then FIRST=false; else RECORDS+=","; fi
  RECORDS+=$(jq -n \
    --arg agent_id "$AGENT_ID" \
    --arg date "$TODAY" \
    --arg timestamp "$TIMESTAMP" \
    --arg content "$CONTENT" \
    '{agent_id: $agent_id, log_date: $date, timestamp: $timestamp, content: $content}')
done

RECORDS+="]"

# Batch insert all memory logs
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${SUPABASE_URL}/rest/v1/memory_logs" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -H "Prefer: return=minimal" \
  -d "$RECORDS")

if [ "$HTTP_CODE" = "201" ]; then
  echo ""
  echo "✅ All ${#AGENTS[@]} agents logged to Supabase memory_logs"
else
  echo ""
  echo "⚠️  Supabase batch insert returned HTTP ${HTTP_CODE}"
fi

echo "✅ Daily memory log complete: ${TIMESTAMP}"
